### PR TITLE
Handle case insensitive response.headers

### PR DESCRIPTION
**Pull request by Natim**
Refs https://stackoverflow.com/questions/44414594/how-to-dict-get-a-case-insensitive-key

It is the most obvious way I found. I guess it is not that bad even if something based on a `toLower` and `Dict.map` seams like a good idea too.

### CODE REVIEW

**Comment by n1k0** [comment]
I'd rather map all header names to lower case, seems cleaner to me.

**Comment by n1k0** [comment]
Hint: http://package.elm-lang.org/packages/elm-community/dict-extra/2.1.0/Dict-Extra#mapKeys

**Review by n1k0 — APPROVED** [review]
I couldn't find tests for header parsing, though it may be worth adding some.

**Comment by Natim** [comment]
I was looking at them actually 👍

**Comment by n1k0** [comment]
We investigated writing a test for `decodePager`, but that would mean exporting it as part of the public API, which wouldn't make any sense. Neither do we want to write a functional test for that. Let's land this.

**Pull request merged**
